services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: es01
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge